= Changelog of the `newdoc` script

== v1.2, WIP

New features:

* You can now configure ID capitalization and word separators in the `~/.config/newdoc/newdoc.ini` config file.

Bug fixes:

* The bundled assembly template no longer includes a non-existent file, and can be compiled with no errors

== v1.1, 2018-07-13

New features:

* `newdoc` is now compatible with Python 2.7, and as such can be run on RHEL 7 or macOS with no additional setup steps.
* The script prints out an (example) include statement after generating a file. This can be used to copy and paste the include into an assembly.

== v1.0, 2018-06-19

Initial version. Features in this release:

* Generates files from four hard-coded templates (assembly, concept, procedure, and reference) located in the `templates/` directory next to the script file itself.
* Fills in the correct ID, title, context, and parent context. Names the resulting file accordingly.
* Has the option to include comments in the generated file or delete them.

