:toc:

[id="readme"]
= README: The `newdoc` script

[id="installation"]
== How do I install the script?

[discrete]
=== Prerequisites

The script requires Python 3.5 or later to run. This is available on Fedora and most other community distributions by default.

* If you are using RHEL 7, install Python 3:
+
--
. Enable Software Collections:
+
----
# subscription-manager repos --enable rhel-server-rhscl-7-rpms
----
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/3.1_release_notes/chap-installation[].

. Install the package containing Python 3:
+
----
# yum install rh-python36
----
--

* If you use a different system that does not contain Python 3, install it in the appropriate way.


[discrete]
=== Procedure

. Clone this repository somewhere on your system:
+
[subs=+quotes]
----
$ git clone git@gitlab.cee.redhat.com:ccs-tools/newdoc.git
----

. In your shell configuration, add an alias to the `newdoc` script.
+
** If you are using Fedora or a community Linux distribution:
+
[subs=+quotes]
----
alias newdoc="_path-to-cloned-repo_/newdoc.py"
----
+
For example, if you are using the `bash` shell, you might add something like the following in your `~/.bashrc` file:
+
[subs=+quotes]
----
alias newdoc="__/home/msuchane/RH/newdoc/__newdoc.py"
----

** If you are using RHEL 7:
+
[subs=+quotes]
----
function newdoc() {
scl enable rh-python36 "_path-to-cloned-repo_/newdoc.py $@"
}
----
+
Or, alternatively:
+
[subs=+quotes]
----
alias newdoc="/opt/rh/rh-python36/root/usr/bin/python _path-to-cloned-repo_/newdoc.py"
----
+
For example, if you are using the `bash` shell, you might add something like the following in your `~/.bashrc` file:
+
[subs=+quotes]
----
function newdoc() {
scl enable rh-python36 "__/home/msuchane/RH/newdoc/__newdoc.py $@"
}
----


If you prefer `newdoc` to generate file without the explanatory comments, change the alias to include the `--no-comments` option:

[subs=+quotes]
----
alias newdoc="__/home/msuchane/RH/newdoc/__newdoc.py *--no-comments*"
----

[id="new-module"]
== How do I add a new module?

[discrete]
=== Prerequisites

* Install the script. See xref:installation[] for details.

[discrete]
=== Procedure

. In the directory where modules are located, use the `newdoc` script to create a new file:
+
[subs=+quotes]
----
_modules-dir_]$ newdoc _--procedure_ "_Setting up thing_"
----
+
The script also accepts the `--concept` and `--reference` options. You can use these short forms instead: `-p`, `-c`, and `-r`.

. Rewrite the information in the template with your docs.

[id="new-assembly"]
== How do I add a new assembly?

[discrete]
=== Prerequisites

* Install the script. See xref:installation[] for details.

[discrete]
=== Procedure

. In the directory where assemblies are located, use the `newdoc` script to create a new file:
+
[subs=+quotes]
----
_assemblies-dir_]$ newdoc --assembly "_Achieving thing_"
----
+
You can use the short form of the option instead: `newdoc -a "_Achieving thing_"`.

. Rewrite the information in the template with your docs.
+
Add AsciiDoc include statements to include modules. See link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files[Include Files] in the AsciiDoc Syntax Quick Reference.


== Additional resources

* link:https://redhat-documentation.github.io/modular-docs/[Modular Documentation Reference Guide]
* link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[AsciiDoc Mark-up Quick Reference for Red Hat Documentation]

