= Changelog of the `newdoc` script

== v1.4.0, 2019-08-29

New features:

* newdoc is now packaged as an RPM on Copr: link:https://copr.fedorainfracloud.org/coprs/mareksu/newdoc/[].
* Templates have been updated to match the upstream modular guidelines.

== v1.3, 2018-08-22

New features:

* The project has been restructured to follow Python packaging standards, and can now be installed from PyPI: link:https://pypi.org/project/newdoc/[].

Bug fixes:

* The generated ID will no longer contain double dashes (`--`). These were breaking references to the ID.

== v1.2, 2018-07-13

New features:

* The script now recognizes the `~/.config/newdoc/newdoc.ini` config file (different on macOS). You can use it to set:
** ID capitalization,
** Word separators in the ID,
** Custom template files.
* Built-in Python templating is used for substitutions in templates. Thanks to this, writing custom templates is more predictable and better documented.

Bug fixes:

* The bundled assembly template no longer includes a non-existent file, and can be compiled with no errors
* The generated IDs no longer start with the module prefix like file names.

== v1.1, 2018-07-13

New features:

* `newdoc` is now compatible with Python 2.7, and as such can be run on RHEL 7 or macOS with no additional setup steps.
* The script prints out an (example) include statement after generating a file. This can be used to copy and paste the include into an assembly.

== v1.0, 2018-06-19

Initial version. Features in this release:

* Generates files from four hard-coded templates (assembly, concept, procedure, and reference) located in the `templates/` directory next to the script file itself.
* Fills in the correct ID, title, context, and parent context. Names the resulting file accordingly.
* Has the option to include comments in the generated file or delete them.

